# 应用配置
spring:
  application:
    name: qiaoqiao-match-three

  # 数据库配置
  datasource:
    url: jdbc:h2:mem:qiaoqiaodb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA配置
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2控制台配置（开发环境）
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  # Thymeleaf配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  # 静态资源配置
  resources:
    static-locations: classpath:/static/
    cache:
      period: 3600

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  # Jackson配置
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
    min-response-size: 1024

# 日志配置
logging:
  level:
    root: INFO
    com.qiaoqiao: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
  file:
    name: logs/qiaoqiao.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 游戏配置
game:
  default-board-size: 8
  default-moves: 20
  min-match-length: 3
  tile-types:
    - 红色
    - 蓝色
    - 绿色
    - 黄色
    - 紫色
  score-settings:
    score-per-tile: 10
    combo-multiplier: 1.5
    special-tile-bonus: 50